// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkZV2Ulhj5DzrJ1IGWSANkIGr5-6F7mak',
    appId: '1:331755052940:web:e9d706dcc6ee4ab11dc0a9',
    messagingSenderId: '331755052940',
    projectId: 'alamode-3f621',
    authDomain: 'alamode-3f621.firebaseapp.com',
    storageBucket: 'alamode-3f621.appspot.com',
    measurementId: 'G-8J9XMF48CC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiYbcS5iJ-JK_ei954nnNwxMNWlnM1mbI',
    appId: '1:331755052940:android:10b319d1bf74f6cb1dc0a9',
    messagingSenderId: '331755052940',
    projectId: 'alamode-3f621',
    storageBucket: 'alamode-3f621.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJnhpLSvJpGnE9mvPmLPWjVjquleVh8o8',
    appId: '1:331755052940:ios:85e61649ed2145441dc0a9',
    messagingSenderId: '331755052940',
    projectId: 'alamode-3f621',
    storageBucket: 'alamode-3f621.appspot.com',
    iosBundleId: 'com.example.alamode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJnhpLSvJpGnE9mvPmLPWjVjquleVh8o8',
    appId: '1:331755052940:ios:85e61649ed2145441dc0a9',
    messagingSenderId: '331755052940',
    projectId: 'alamode-3f621',
    storageBucket: 'alamode-3f621.appspot.com',
    iosBundleId: 'com.example.alamode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkZV2Ulhj5DzrJ1IGWSANkIGr5-6F7mak',
    appId: '1:331755052940:web:99c694ea60a8e19b1dc0a9',
    messagingSenderId: '331755052940',
    projectId: 'alamode-3f621',
    authDomain: 'alamode-3f621.firebaseapp.com',
    storageBucket: 'alamode-3f621.appspot.com',
    measurementId: 'G-PVFSDH1ZYR',
  );
}
